"""Add adapter energy load curve widgets

Revision ID: 1e5c53345116
Revises: b1a025954a9d
Create Date: 2024-07-16 00:53:22.834466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5c53345116'
down_revision = 'b1a025954a9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_load_curve_electric_widget',
    sa.Column('electric_widget_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('electric_dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('electric_widget_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_load_curve_electric_widget')
    # ### end Alembic commands ###
