"""zone temps feature tag

Revision ID: 3119e4929e97
Revises: 5f8aea85777c
Create Date: 2024-08-02 20:12:27.707942

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '3119e4929e97'
down_revision = '5f8aea85777c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'organizationfeaturetoggleenum', ['alert_center', 'auto_configure', 'manual_overrides', 'auto_changeover', 'zone_temperatures'],
                        [TableReference(table_schema='public', table_name='organization_feature_toggles', column_name='organization_feature_toggle')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'organizationfeaturetoggleenum', ['alert_center', 'auto_configure', 'manual_overrides', 'auto_changeover'],
                        [TableReference(table_schema='public', table_name='organization_feature_toggles', column_name='organization_feature_toggle')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
