"""Add control zone temperature place links

Revision ID: 33285d4ddcee
Revises: c3efde473f0d
Create Date: 2024-07-25 01:48:39.819363

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33285d4ddcee'
down_revision = 'c3efde473f0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('input_duct', 'output_duct', 'room', name='controlzonetemperatureplacetype').create(op.get_bind())
    op.create_table('control_zone_temperature_place_links',
    sa.Column('hvac_widget_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_place_id', sa.Uuid(), nullable=False),
    sa.Column('control_zone_temperature_place_type', postgresql.ENUM('input_duct', 'output_duct', 'room', name='controlzonetemperatureplacetype', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hvac_widget_id'], ['control_zone_hvac_widgets.hvac_widget_id'], ),
    sa.PrimaryKeyConstraint('hvac_widget_id', 'temperature_place_id')
    )
    op.sync_enum_values('public', 'thermostatlockouttype', ['Locked', 'Unlocked', 'NotLocked'],
                        [TableReference(table_schema='public', table_name='thermostats', column_name='keypad_lockout')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'thermostatlockouttype', ['Locked', 'Unlocked'],
                        [TableReference(table_schema='public', table_name='thermostats', column_name='keypad_lockout')],
                        enum_values_to_rename=[])
    op.drop_table('control_zone_temperature_place_links')
    sa.Enum('input_duct', 'output_duct', 'room', name='controlzonetemperatureplacetype').drop(op.get_bind())
    # ### end Alembic commands ###
