"""Add modbus_address to thermostats

Revision ID: 3ca00ab02893
Revises: 035c74ece7ba
Create Date: 2024-08-18 21:08:59.712835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca00ab02893'
down_revision = '035c74ece7ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thermostats', sa.Column('modbus_address', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thermostats', 'modbus_address')
    # ### end Alembic commands ###
