"""Add adapter hvac schedule/events and control zone widget

Revision ID: 4ac2fe81068e
Revises: b6fa261ba27b
Create Date: 2024-07-23 03:41:52.215459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ac2fe81068e'
down_revision = 'b6fa261ba27b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('cooling', 'heating', 'auto', 'off', name='hvacschedulemode').create(op.get_bind())
    op.create_table('hvac_schedules',
    sa.Column('hvac_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hvac_schedule_id')
    )
    op.create_table('control_zone_hvac_widgets',
    sa.Column('hvac_widget_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monday_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('tuesday_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('wednesday_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('thursday_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('friday_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('saturday_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('sunday_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('hvac_dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friday_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.ForeignKeyConstraint(['monday_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.ForeignKeyConstraint(['saturday_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.ForeignKeyConstraint(['sunday_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.ForeignKeyConstraint(['thursday_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.ForeignKeyConstraint(['tuesday_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.ForeignKeyConstraint(['wednesday_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.PrimaryKeyConstraint('hvac_widget_id')
    )
    op.create_table('hvac_schedule_events',
    sa.Column('hvac_schedule_event_id', sa.Uuid(), nullable=False),
    sa.Column('hvac_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('mode', postgresql.ENUM('cooling', 'heating', 'auto', 'off', name='hvacschedulemode', create_type=False), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('set_point_c', sa.Float(), nullable=True),
    sa.Column('set_point_heating_c', sa.Float(), nullable=True),
    sa.Column('set_point_cooling_c', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hvac_schedule_id'], ['hvac_schedules.hvac_schedule_id'], ),
    sa.PrimaryKeyConstraint('hvac_schedule_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hvacschedules')
    op.drop_table('control_zone_hvac_widgets')
    op.drop_table('hvac_schedules')
    sa.Enum('cooling', 'heating', 'auto', 'off', name='hvacschedulemode').drop(op.get_bind())
    # ### end Alembic commands ###
