"""Add access scope and roles

Revision ID: 504630988dda
Revises: dd5dc40768a3
Create Date: 2024-06-20 15:13:47.302842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504630988dda'
down_revision = '598c6d9de14e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_role_access_scopes',
    sa.Column('access_role_id', sa.Uuid(), nullable=False),
    sa.Column('access_scope', sa.Enum('admin:admin', 'appliances:write', 'appliances:read', 'electricity_monitoring:write', 'electricity_monitoring:read', 'locations:write', 'locations:read', 'location_operating_hours:write', 'location_operating_hours:read', 'mesh_networks:write', 'mesh_networks:read', 'organizations:write', 'organizations:read', 'organization_users:write', 'organization_users:read', 'temperature_monitoring:write', 'temperature_monitoring:read', 'users:write', 'users:read', name='accessscope'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('access_role_id', 'access_scope')
    )
    op.create_table('access_roles',
    sa.Column('access_role_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('access_role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_access_scopes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_scope', sa.Enum('admin:admin', 'appliances:write', 'appliances:read', 'electricity_monitoring:write', 'electricity_monitoring:read', 'locations:write', 'locations:read', 'location_operating_hours:write', 'location_operating_hours:read', 'mesh_networks:write', 'mesh_networks:read', 'organizations:write', 'organizations:read', 'organization_users:write', 'organization_users:read', 'temperature_monitoring:write', 'temperature_monitoring:read', 'users:write', 'users:read', name='accessscope'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'access_scope')
    )
    op.create_table('user_access_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'access_role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_access_roles')
    op.drop_table('user_access_scopes')
    op.drop_table('access_roles')
    op.drop_table('access_role_access_scopes')
    # ### end Alembic commands ###
