"""Add temperature ranges

Revision ID: 598c6d9de14e
Revises: c1815d3fa89d
Create Date: 2024-06-14 18:15:25.363203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598c6d9de14e'
down_revision = 'c1815d3fa89d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_ranges',
    sa.Column('temperature_range_id', sa.Uuid(), nullable=False),
    sa.Column('high_degrees_celcius', sa.Float(), nullable=False),
    sa.Column('low_degrees_celcius', sa.Float(), nullable=False),
    sa.Column('warning_level', sa.Enum('GOOD', 'WARNING', 'DANGER', name='temperaturerangewarninglevelenum'), nullable=False),
    sa.Column('temperature_sensor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('temperature_range_id'),
    sa.UniqueConstraint('temperature_sensor_id', 'high_degrees_celcius', 'low_degrees_celcius', 'warning_level', name='_temperature_range_unique_table_constraint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature_ranges')
    # ### end Alembic commands ###
