"""Add adapter temperature dashboard and widgets

Revision ID: 5b5eb7f9d21a
Revises: 5fca6df76ac3
Create Date: 2024-07-11 03:54:34.420397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b5eb7f9d21a'
down_revision = '5fca6df76ac3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_dashboards',
    sa.Column('temperature_dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('temperature_dashboard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature_dashboards')
    # ### end Alembic commands ###
