"""Remove temp unit widget composite pk

Revision ID: 5cb3794354af
Revises: a34615b441e6
Create Date: 2024-10-30 19:14:14.328518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb3794354af'
down_revision = 'a34615b441e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key('pk_temperature_unit_widget', 'temperature_unit_widgets', ['temperature_unit_widget_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_temperature_unit_widget', 'temperature_unit_widgets', type_='primary')
    # ### end Alembic commands ###
