"""operating range notifcations

Revision ID: 5f8aea85777c
Revises: db49209a25d9
Create Date: 2024-08-01 21:47:38.656197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f8aea85777c'
down_revision = 'db49209a25d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_range_notification_settings',
    sa.Column('operating_range_notification_settings_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('allow_emails', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('operating_range_notification_settings_id'),
    sa.UniqueConstraint('user_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operating_range_notification_settings')
    # ### end Alembic commands ###
