"""Add adapter electric dashboard and widgets

Revision ID: 5fca6df76ac3
Revises: 6537f830fe8b
Create Date: 2024-07-11 03:25:25.556358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fca6df76ac3'
down_revision = '9466e1050562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electric_dashboards',
    sa.Column('electric_dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('electric_dashboard_id')
    )
    op.create_table('energy_consumption_breakdown_electric_widget',
    sa.Column('electric_widget_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('electric_dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('electric_widget_id')
    ) 
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_consumption_breakdown_electric_widget')
    op.drop_table('electric_dashboards')
    # ### end Alembic commands ###
