"""Add location operating hours

Revision ID: 6537f830fe8b
Revises: 6ecf271d200d
Create Date: 2024-07-03 19:53:36.268671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6537f830fe8b'
down_revision = '33f4be5fd593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_operating_hours',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Enum('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='dayofweek'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('work_start_time', sa.Time(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('work_end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('location_id', 'day_of_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_operating_hours')
    # ### end Alembic commands ###
