"""Add temperature sensor alerts

Revision ID: 6ecf271d200d
Revises: 504630988dda
Create Date: 2024-07-02 14:44:14.597089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecf271d200d'
down_revision = '504630988dda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_sensor_place_alerts',
    sa.Column('temperature_sensor_place_alert_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_sensor_place_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('above_normal_operating_range', 'below_normal_operating_range', name='temperaturesensorplacealerttype'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('threshold_temperature_c', sa.Float(), nullable=False),
    sa.Column('threshold_window_seconds', sa.Integer(), nullable=False),
    sa.Column('reporter_temperature_c', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('temperature_sensor_place_alert_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature_sensor_place_alerts')
    # ### end Alembic commands ###
