"""Update access grants

Revision ID: 819f6c54069f
Revises: 9514fbe66644
Create Date: 2024-07-25 22:00:46.326295

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '819f6c54069f'
down_revision = '9514fbe66644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.sync_enum_values('public', 'organizationaccessgrant', ['ALLOW_READ_ORGANIZATION', 'ALLOW_UPDATE_ORGANIZATION', 'ALLOW_CREATE_LOCATION', 'ALLOW_READ_LOCATION', 'ALLOW_UPDATE_LOCATION'],
                        [TableReference(table_schema='public', table_name='user_organization_access_grants', column_name='organization_access_grant')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'locationaccessgrant', ['ALLOW_READ_LOCATION', 'ALLOW_UPDATE_LOCATION'],
                        [TableReference(table_schema='public', table_name='user_location_access_grants', column_name='location_access_grant')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'locationaccessgrant', ['ALLOW_CREATE_LOCATION', 'ALLOW_READ_LOCATION', 'ALLOW_UPDATE_LOCATION'],
                        [TableReference(table_schema='public', table_name='user_location_access_grants', column_name='location_access_grant')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'organizationaccessgrant', ['ALLOW_READ_ORGANIZATION', 'ALLOW_UPDATE_ORGANIZATION'],
                        [TableReference(table_schema='public', table_name='user_organization_access_grants', column_name='organization_access_grant')],
                        enum_values_to_rename=[])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
