"""optional api key name

Revision ID: 83f5b2411003
Revises: f7226f347162
Create Date: 2025-02-19 16:37:26.509750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f5b2411003'
down_revision = 'f7226f347162'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'api_keys', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
