"""Add temperature sensor places

Revision ID: 9466e1050562
Revises: 6537f830fe8b
Create Date: 2024-07-11 18:44:25.464112

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '9466e1050562'
down_revision = '6537f830fe8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_sensor_places',
    sa.Column('temperature_sensor_place_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('temperature_sensor_place_id'),
    sa.UniqueConstraint('location_id', 'name', name='_temperature_sensor_place_unique_table_constraint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature_sensor_places')
    # ### end Alembic commands ###
