"""organization and location access grants

Revision ID: 9514fbe66644
Revises: e8b2f3d56e7f
Create Date: 2024-07-25 19:30:02.374546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9514fbe66644'
down_revision = 'e8b2f3d56e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ALLOW_CREATE_LOCATION', 'ALLOW_READ_LOCATION', 'ALLOW_UPDATE_LOCATION', name='locationaccessgrant').create(op.get_bind())
    sa.Enum('ALLOW_READ_ORGANIZATION', 'ALLOW_UPDATE_ORGANIZATION', name='organizationaccessgrant').create(op.get_bind())
    op.create_table('user_location_access_grants',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('location_access_grant', postgresql.ENUM('ALLOW_CREATE_LOCATION', 'ALLOW_READ_LOCATION', 'ALLOW_UPDATE_LOCATION', name='locationaccessgrant', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'location_id', 'location_access_grant')
    )
    op.create_table('user_organization_access_grants',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('organization_access_grant', postgresql.ENUM('ALLOW_READ_ORGANIZATION', 'ALLOW_UPDATE_ORGANIZATION', name='organizationaccessgrant', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'organization_id', 'organization_access_grant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_organization_access_grants')
    op.drop_table('user_location_access_grants')
    sa.Enum('ALLOW_READ_ORGANIZATION', 'ALLOW_UPDATE_ORGANIZATION', name='organizationaccessgrant').drop(op.get_bind())
    sa.Enum('ALLOW_CREATE_LOCATION', 'ALLOW_READ_LOCATION', 'ALLOW_UPDATE_LOCATION', name='locationaccessgrant').drop(op.get_bind())
    # ### end Alembic commands ###
