"""hvac schedule cascades

Revision ID: a4d8ab3300dd
Revises: 4392c9e1fcf4
Create Date: 2024-09-13 22:25:41.143262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d8ab3300dd'
down_revision = '4392c9e1fcf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hvac_schedule_events_hvac_schedule_id_fkey', 'hvac_schedule_events', type_='foreignkey')
    op.create_foreign_key(None, 'hvac_schedule_events', 'hvac_schedules', ['hvac_schedule_id'], ['hvac_schedule_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hvac_schedule_events', type_='foreignkey')
    op.create_foreign_key('hvac_schedule_events_hvac_schedule_id_fkey', 'hvac_schedule_events', 'hvac_schedules', ['hvac_schedule_id'], ['hvac_schedule_id'])
    # ### end Alembic commands ###
