"""Update temperature range columns

Revision ID: b3a480f5157a
Revises: df4744a65083
Create Date: 2024-08-07 18:33:31.575996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a480f5157a'
down_revision = 'df4744a65083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature_ranges', sa.Column('temperature_sensor_place_id', sa.Uuid(), nullable=False))
    op.drop_constraint('_temperature_range_unique_table_constraint', 'temperature_ranges', type_='unique')
    op.create_unique_constraint('_temperature_range_unique_table_constraint', 'temperature_ranges', ['temperature_sensor_place_id', 'high_degrees_celcius', 'low_degrees_celcius', 'warning_level'])
    op.drop_column('temperature_ranges', 'temperature_sensor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature_ranges', sa.Column('temperature_sensor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('_temperature_range_unique_table_constraint', 'temperature_ranges', type_='unique')
    op.create_unique_constraint('_temperature_range_unique_table_constraint', 'temperature_ranges', ['temperature_sensor_id', 'high_degrees_celcius', 'low_degrees_celcius', 'warning_level'])
    op.drop_column('temperature_ranges', 'temperature_sensor_place_id')
    # ### end Alembic commands ###
