"""Add adapter hvac dashboards

Revision ID: b6fa261ba27b
Revises: 2c3194b41591
Create Date: 2024-07-22 16:28:35.938308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fa261ba27b'
down_revision = '2c3194b41591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hvac_dashboards',
    sa.Column('hvac_dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hvac_dashboard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hvac_dashboards')
    # ### end Alembic commands ###
