"""Optional electric sensor panel

Revision ID: b97099897e3a
Revises: c94b00305518
Create Date: 2025-03-12 20:02:00.381251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97099897e3a'
down_revision = 'c94b00305518'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electric_sensors', 'electric_panel_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('electric_sensors', 'electric_panel_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
