"""Add temperature sensors

Revision ID: c1815d3fa89d
Revises: dd5dc40768a3
Create Date: 2024-06-14 15:52:03.625610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1815d3fa89d'
down_revision = 'dd5dc40768a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_sensors',
    sa.Column('temperature_sensor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duid', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('APPLIANCE', 'ZONE', name='temperaturesensortypeenum'), nullable=False),
    sa.Column('make', sa.Enum('RUUVI', 'MINEW', name='temperaturesensormakeenum'), nullable=False),
    sa.Column('model', sa.Enum('RUUVI_TAG', 'S1', 'MST01_01', 'MST01_04', name='temperaturesensormodelenum'), nullable=False),
    sa.Column('gateway_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('temperature_sensor_id'),
    sa.UniqueConstraint('duid')
    )
    op.drop_constraint('_clamps_unique_table_constraint', 'clamps', type_='unique')
    op.create_unique_constraint('_clamps_unique_table_constraint', 'clamps', ['circuit_id', 'port_name', 'port_pin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_clamps_unique_table_constraint', 'clamps', type_='unique')
    op.create_unique_constraint('_clamps_unique_table_constraint', 'clamps', ['name', 'circuit_id', 'phase'])
    op.drop_table('temperature_sensors')
    # ### end Alembic commands ###
