"""add appliances service

Revision ID: c93049748138
Revises: 217a95643936
Create Date: 2024-06-05 20:31:07.582727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93049748138'
down_revision = '217a95643936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliance_type',
    sa.Column('appliance_type_id', sa.Uuid(), nullable=False),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('subtype', sa.String(length=255), nullable=True),
    sa.Column('year_manufactured', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('appliance_type_id'),
    sa.UniqueConstraint('make', 'model', 'type', 'subtype', 'year_manufactured', name='_appliance_type_unique_table_constraint')
    )
    op.create_table('appliances',
    sa.Column('appliance_id', sa.Uuid(), nullable=False),
    sa.Column('appliance_type_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('circuit_id', sa.Uuid(), nullable=False),
    sa.Column('temperature_sensor_id', sa.Uuid(), nullable=True),
    sa.Column('serial', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('appliance_id'),
    sa.UniqueConstraint('serial')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appliances')
    op.drop_table('appliance_type')
    # ### end Alembic commands ###
