"""Update mesh networks unique constraint

Revision ID: cd5eed1da0db
Revises: e554d9d016a8
Create Date: 2024-09-18 20:46:19.631169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5eed1da0db'
down_revision = 'e554d9d016a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('standard', 'modbus', name='nodetypeenum').create(op.get_bind())
    op.create_unique_constraint('_gateways_unique_table_constraint', 'gateways', ['location_id', 'name'])
    op.alter_column('nodes', 'type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('standard', 'modbus', name='nodetypeenum'),
               existing_nullable=False,
               postgresql_using='type::nodetypeenum')
    op.drop_constraint('nodes_name_key', 'nodes', type_='unique')
    op.create_unique_constraint('_nodes_unique_table_constraint', 'nodes', ['gateway_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_nodes_unique_table_constraint', 'nodes', type_='unique')
    op.create_unique_constraint('nodes_name_key', 'nodes', ['name'])
    op.alter_column('nodes', 'type',
               existing_type=sa.Enum('standard', 'modbus', name='nodetypeenum'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint('_gateways_unique_table_constraint', 'gateways', type_='unique')
    sa.Enum('standard', 'modbus', name='nodetypeenum').drop(op.get_bind())
    # ### end Alembic commands ###
