"""location electricity prices

Revision ID: d41eceb1d3b7
Revises: 819f6c54069f
Create Date: 2024-07-31 22:49:51.990918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41eceb1d3b7'
down_revision = '819f6c54069f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_electricity_prices',
    sa.Column('location_electricity_price_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('location_electricity_price_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_electricity_prices')
    # ### end Alembic commands ###
