"""Update clamp unique constraint

Revision ID: e554d9d016a8
Revises: a4d8ab3300dd
Create Date: 2024-09-18 19:56:23.880472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e554d9d016a8'
down_revision = 'a4d8ab3300dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_clamps_unique_table_constraint', 'clamps', type_='unique')
    op.create_unique_constraint('_clamps_unique_table_constraint', 'clamps', ['electric_sensor_id', 'port_name', 'port_pin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_clamps_unique_table_constraint', 'clamps', type_='unique')
    op.create_unique_constraint('_clamps_unique_table_constraint', 'clamps', ['circuit_id', 'port_name', 'port_pin'])
    # ### end Alembic commands ###
