"""Update thermostat model enum

Revision ID: e614e8b219c1
Revises: 684089c52d10
Create Date: 2024-10-25 16:48:55.010841

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'e614e8b219c1'
down_revision = '684089c52d10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'thermostatmodelenum', ['BC103S-ACDM-24'],
                        [TableReference(table_schema='public', table_name='thermostats', column_name='model')],
                        enum_values_to_rename=[('v1', 'BC103S-ACDM-24')])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'thermostatmodelenum', ['v1'],
                        [TableReference(table_schema='public', table_name='thermostats', column_name='model')],
                        enum_values_to_rename=[('BC103S-ACDM-24', 'v1')])
    # ### end Alembic commands ###
