"""Organization feature toggles

Revision ID: e8b2f3d56e7f
Revises: 33285d4ddcee
Create Date: 2024-07-25 04:42:54.224508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8b2f3d56e7f'
down_revision = '33285d4ddcee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('alert_center', 'auto_configure', 'manual_overrides', 'auto_changeover', name='organizationfeaturetoggleenum').create(op.get_bind())
    op.create_table('organization_feature_toggles',
    sa.Column('organization_feature_toggle_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('organization_feature_toggle', postgresql.ENUM('alert_center', 'auto_configure', 'manual_overrides', 'auto_changeover', name='organizationfeaturetoggleenum', create_type=False), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('organization_feature_toggle_id')
    )
    op.add_column('organization_users', sa.Column('is_organization_owner', sa.Boolean(), nullable=False))
    op.add_column('organization_users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('organizations', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organization_users', 'updated_at')
    op.drop_column('organization_users', 'is_organization_owner')
    op.drop_table('organization_feature_toggles')
    sa.Enum('alert_center', 'auto_configure', 'manual_overrides', 'auto_changeover', name='organizationfeaturetoggleenum').drop(op.get_bind())
    # ### end Alembic commands ###
