"""Optional expire at actual field for hvac holds

Revision ID: fdb924c33627
Revises: 6ebc944fff01
Create Date: 2024-09-12 18:56:27.593964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdb924c33627'
down_revision = '6ebc944fff01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hvac_holds', 'expire_at_actual',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hvac_holds', 'expire_at_actual',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
