name: powerx-api

services:

  # PowerX API
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "alembic upgrade head && python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips '*'"
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DEBUG=1
      - PX_LOGGING_LEVEL=DEBUG
    env_file:
      - ./envs/.env.dev
      - ./.env
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./alembic:/app/alembic
      - ~/.aws:/root/.aws:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # PostgreSQL Database
  postgres:
    image: postgres:16.8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POWERX_DATABASE_NAME}
      POSTGRES_USER: ${POWERX_DATABASE_USER}
      POSTGRES_PASSWORD: ${POWERX_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@powerx.co
      PGADMIN_DEFAULT_PASSWORD: powerxisneat
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin-data:
